server:
  port: 8080
  servlet:
    context-path: /
spring:
  profiles:
    #环境选择
    active: dev
  cache:
    jcache:
      config: classpath:ehcache3.xml
  #2.0之后文件上传限制配置
  servlet:
    multipart:
      #单个文件大小
      max-file-size: 10MB
      #总文件大小
      max-request-size: 10MB

#配置mybatis
mybatis:
  #配置*.xml输入
  mapper-locations: classpath:mapper/*.xml
  #配置实体类别名
  type-aliases-package: com.yj.model

#配置日志输出文件配置
logging:
  config: classpath:logback-spring.xml

#pagehelper
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
#    returnPageInfo: check
